javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/model/jpa/ImageSlideElement.java
package com.aiconoa.trainings.javaee7.slideshow.model.jpa;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@Entity
@DiscriminatorValue(value="image")
public class ImageSlideElement extends SlideElementBaseEntity<String> {
    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        return "ImageSlideElement [id=" + id + ", getX()=" + getX() + ", getY()=" + getY() + ", getWidth()="
                + getWidth() + ", getHeight()=" + getHeight() + ", getContent()=" + getContent() + ", toString()="
                + super.toString() + ", getClass()=" + getClass() + ", hashCode()=" + hashCode() + "]";
    }


}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/model/jpa/TextSlideElement.java
package com.aiconoa.trainings.javaee7.slideshow.model.jpa;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@Entity
@DiscriminatorValue(value="text")
public class TextSlideElement extends SlideElementBaseEntity<String> {
    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        return "TextSlideElement [id=" + id + ", getX()=" + getX() + ", getY()=" + getY() + ", getWidth()=" + getWidth()
                + ", getHeight()=" + getHeight() + ", getContent()=" + getContent() + ", toString()=" + super.toString()
                + ", getClass()=" + getClass() + ", hashCode()=" + hashCode() + "]";
    }
    
    
}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/model/nonjpa/ImageSlideElement.java
package com.aiconoa.trainings.javaee7.slideshow.model.nonjpa;

public class ImageSlideElement extends SlideElementBase<String> {

}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/model/nonjpa/TextSlideElement.java
package com.aiconoa.trainings.javaee7.slideshow.model.nonjpa;

public class TextSlideElement extends SlideElementBase<String> {

}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/jsf/SlideshowBean.java
package com.aiconoa.trainings.javaee7.slideshow.jsf;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.aiconoa.trainings.javaee7.slideshow.model.jpa.ImageSlideElement;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.Slide;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.SlideElement;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.Slideshow;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.TextSlideElement;
import com.aiconoa.trainings.javaee7.slideshow.service.SlideshowServiceEJB;

@Named
@SessionScoped
public class SlideshowBean implements Serializable {
    private static final long serialVersionUID = 1L;

    private static Logger LOGGER = Logger.getLogger(SlideshowBean.class.getName());
    
    @Inject
    private SlideshowServiceEJB slideshowService;
    
    private Integer id;
    
    transient private Integer index;

    private Slideshow slideshow;
    private Slide slide;
    
    private Map<Integer, Integer> lastVisitedSlidePerSlideshow = new HashMap<>();
    
    public Integer getId() {
        return id;
    }
    
    public Integer getIndex() {
        return index;
    }
    
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public void setIndex(Integer index) {
        this.index = index;
    }
    
    public String load() {
        LOGGER.info(String.format("SlideshowBean#load %d %d",id, index ));
        if (this.index == null) { // si pas d'index => rediriger vers le dernier index connu ou 0
            LOGGER.info(String.format("SlideshowBean#load %d %d",id, index ));
            return String.format("/slideshow-jsf/slideshow.xhtml?faces-redirect=true&id=%s&index=%s", 
                    this.id, lastVisitedSlidePerSlideshow.getOrDefault(this.id, 0));
            // FacesContext.getCurrentInstance().getExternalContext().redirect()
        }
        
        this.slideshow = slideshowService.findSlideshow(this.id);
        this.slide = slideshow.getSlideAt(this.index);
        this.lastVisitedSlidePerSlideshow.put(this.id, this.index);
        
        return null;
    }
    
    public Slideshow getSlideshow() {
        return slideshow;
    }
    
    public Slide getSlide() {
        return slide;
    }
    
    public String generateHTMLMarkupForSlideElement(SlideElement<?> se) {
        if(se instanceof TextSlideElement) {
            TextSlideElement e = (TextSlideElement) se;
            return String.format("<text text-anchor=\"middle\" alignment-baseline=\"middle\" x=\"%f\"  y=\"%f\" font-family=\"Helvetica\" font-size=\"40\"  fill=\"black\">%s</text>", e.getX(), e.getY(), e.getContent());                    
        } else if (se instanceof ImageSlideElement) {
            ImageSlideElement e = (ImageSlideElement) se;            
            return String.format("<image xlink:href=\"/javaee7/img?img=%s\" x=\"%f\" y=\"%f\" width=\"%f\" height=\"%f\" preserveAspectRatio=\"xMidYMid meet\"/>", e.getContent(), e.getX(), e.getY(), e.getWidth(), e.getHeight());
        }
        
        return "";
    }
    
    
    
}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/jsf/SlideshowListBean.java
package com.aiconoa.trainings.javaee7.slideshow.jsf;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.aiconoa.trainings.javaee7.slideshow.model.jpa.Slideshow;
import com.aiconoa.trainings.javaee7.slideshow.service.SlideshowServiceEJB;

@Named
@RequestScoped
public class SlideshowListBean {
    
    private static Logger LOGGER = Logger.getLogger(SlideshowListBean.class.getName());
    
    @Inject
    private SlideshowServiceEJB slideshowService;
    
    private List<Slideshow> slideshowListCache;
    
    private List<String> slideshowThumbnails;

    @PostConstruct
    private void init() {
        slideshowListCache = slideshowService.findAllSlideshow();
        
        slideshowThumbnails = new ArrayList<String>();
        for (Slideshow slideshow : slideshowListCache) {
            // can optimize this => one request fetches all thumbnails
            slideshowThumbnails.add(slideshowService.findFirstImageInASlideOfTheSlideshow(slideshow.getId()));
        }
    }

    public List<Slideshow> getSlideshows() {
        LOGGER.info("SlideshowListBean#getSlideshows");
        return slideshowListCache;
    }
    
    public List<String> getSlideshowThumbnails() {
        return slideshowThumbnails;
    }

}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/servlet/ImgDownloadServlet.java
package com.aiconoa.trainings.javaee7.slideshow.servlet;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("img")
public class ImgDownloadServlet extends HttpServlet {
    
    private static final Logger LOGGER = Logger.getLogger(ImgDownloadServlet.class.getName());
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        String imgName = req.getParameter("img");
        
        // déduire un mime-type en adéquation avec le imgName
        resp.addHeader("Content-Type", "image/jpeg");

        // resp.addHeader("Content-Disposition", "attachement; filename=serlvet-spec.pdf");

        
        // ATTENTION GROSSE FAILLE DE SECURITE, BIEN SECURISER l'ACCES AU NOM DE FICHIER...
        String path = "/Users/thomasgros/Desktop/upload/" + imgName;
        FileInputStream fis = new FileInputStream(path);
        LOGGER.info("asked to download image at " + path);
        
        BufferedInputStream bis = new BufferedInputStream(fis);
        
        byte[] buffer = new byte[8192];
        int length;
        while( (length = bis.read(buffer)) != -1) {
            resp.getOutputStream().write(buffer, 0, length);
        }
        
        bis.close();
        resp.getOutputStream().flush();

    }
    
}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/servlet/SlideshowJPAServlet.java
package com.aiconoa.trainings.javaee7.slideshow.servlet;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.Resource;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.transaction.UserTransaction;

import com.aiconoa.trainings.javaee7.slideshow.model.jpa.Slide;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.SlideElement;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.Slideshow;

@WebServlet("slideshowjpa")
public class SlideshowJPAServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    private static final Logger LOGGER = Logger.getLogger(SlideshowJPAServlet.class.getName());
    
    @PersistenceUnit(unitName="SlideshowPU")
    private EntityManagerFactory emf;
    
    @Resource
    private UserTransaction utx;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        EntityManager em = emf.createEntityManager(); 

        try {
            utx.begin();

            Slideshow slideshow = em.find(Slideshow.class, 1);

            LOGGER.info(slideshow.toString());
            for(Slide s: slideshow.getSlides()) {
                LOGGER.info(s.toString());
                for(SlideElement<?> se: s.getSlideElements()) {
                    LOGGER.info(se.toString());
                }
            }

            utx.commit();
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Error during the transaction", e);
            try {
                utx.rollback();
            } catch (Exception e2) {
                LOGGER.log(Level.SEVERE, "Error during transaction rollback", e2);
            }
        }

        em.close();
    }
    
}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/servlet/SlideshowJSPEJBServlet.java
package com.aiconoa.trainings.javaee7.slideshow.servlet;

import java.io.IOException;
import java.util.logging.Logger;

import javax.ejb.EJBException;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.aiconoa.trainings.javaee7.slideshow.model.jpa.Slide;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.SlideElement;
import com.aiconoa.trainings.javaee7.slideshow.model.jpa.Slideshow;
import com.aiconoa.trainings.javaee7.slideshow.service.SlideshowServiceEJB;

@WebServlet("slideshowjspejb")
public class SlideshowJSPEJBServlet extends HttpServlet {
    private static final Logger LOGGER = Logger.getLogger(SlideshowJSPEJBServlet.class.getName());
    
    @Inject
    private SlideshowServiceEJB slideshowService;
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        
        LOGGER.info("SlideshowServlet - doGet - " + req.getQueryString());

        String slideshowIdParam = req.getParameter("id");
        
        if(slideshowIdParam == null) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }
        
        
        if(! slideshowIdParam.matches("\\d+")) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "id doit être un entier");
            return;
        }
        
        int slideshowId = Integer.parseInt(slideshowIdParam);
        
        Slideshow slideshow = slideshowService.findSlideshow(slideshowId);
        
        if(slideshow == null) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }   
        
        String slideIndexParam = req.getParameter("index");
        if(slideIndexParam == null) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }
        
        
        if(! slideIndexParam.matches("\\d+")) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "index doit être un entier");
            return;
        }
        
        int slideIndex = Integer.parseInt(slideIndexParam);
        
        
        if(slideIndex < 0 || slideIndex >= slideshow.size()) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }
        
        Slide slide = slideshow.getSlideAt(slideIndex);
        
        req.setAttribute("slideshow", slideshow);

        req.setAttribute("slide", slide);
        req.setAttribute("slideIndex", slideIndex);
        
        LOGGER.info("##########################################");
        
        LOGGER.info(slideshow.toString());
        for(Slide s: slideshow.getSlides()) {
            LOGGER.info(s.toString());
            for(SlideElement<?> se: s.getSlideElements()) {
                LOGGER.info(se.toString());
            }
        }
        
        LOGGER.info("##########################################");
        
        req.getRequestDispatcher("/WEB-INF/slideshow/slideshowejb.jsp")
            .forward(req, resp);
    }
    
}

javaee7wildfly/src/main/java/com/aiconoa/trainings/javaee7/slideshow/servlet/SlideshowJSPServlet.java
package com.aiconoa.trainings.javaee7.slideshow.servlet;

import java.io.IOException;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.aiconoa.trainings.javaee7.servlet.filter.LogFilter;
import com.aiconoa.trainings.javaee7.slideshow.model.nonjpa.ImageSlideElement;
import com.aiconoa.trainings.javaee7.slideshow.model.nonjpa.Slide;
import com.aiconoa.trainings.javaee7.slideshow.model.nonjpa.SlideElement;
import com.aiconoa.trainings.javaee7.slideshow.model.nonjpa.Slideshow;
import com.aiconoa.trainings.javaee7.slideshow.model.nonjpa.TextSlideElement;
import com.aiconoa.trainings.javaee7.slideshow.service.SlideshowService;

@WebServlet("slideshowjsp")
public class SlideshowJSPServlet extends HttpServlet {
    private static final Logger LOGGER = Logger.getLogger(SlideshowJSPServlet.class.getName());
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        LOGGER.info("SlideshowServlet - doGet - " + req.getQueryString());
        
        SlideshowService slideshowService = new SlideshowService();

        String slideshowIdParam = req.getParameter("id");
        
        if(slideshowIdParam == null) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }
        
        
        if(! slideshowIdParam.matches("\\d+")) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "id doit être un entier");
            return;
        }
        
        int slideshowId = Integer.parseInt(slideshowIdParam);
        
        Slideshow slideshow = slideshowService.findSlideshow(slideshowId);
        if(slideshow == null) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }   
        
        String slideIndexParam = req.getParameter("index");
        if(slideIndexParam == null) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }
        
        
        if(! slideIndexParam.matches("\\d+")) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "index doit être un entier");
            return;
        }
        
        int slideIndex = Integer.parseInt(slideIndexParam);
        
        
        if(slideIndex < 0 || slideIndex >= slideshow.size()) {           
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "la page demandée n'existe pas");
            return;
        }
        
        Slide slide = slideshow.getSlideAt(slideIndex);
        
        req.setAttribute("slideshow", slideshow);
        req.setAttribute("slide", slide);
        req.setAttribute("slideIndex", slideIndex);
        
        req.getRequestDispatcher("/WEB-INF/slideshow/slideshow.jsp")
            .forward(req, resp);
    }
    
}

javaee7wildfly/src/main/webapp/slideshow-jsf/slideshow-list.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Slideshows</title>
    <h:outputStylesheet name="css/slideshow-list.css" />
</h:head>
<body>
<p>Les slideshow disponibles</p>
<div class="slideshow-gallery">
<ui:repeat value="#{slideshowListBean.slideshows}" 
           var="slideshow"
           varStatus="myVarStatus">
    <h:link outcome="/slideshow-jsf/slideshow" class="slideshow-gallery__item">
        <f:param name="id" value="#{slideshow.id}" />
        <img class="slideshow-gallery__item__image" src="/javaee7/img?img=#{slideshowListBean.slideshowThumbnails[myVarStatus.index] }" alt="" />
        <p class="slideshow-gallery__item__title">#{ slideshow.title}</p>
    </h:link>
<!-- 	<a href="" class="slideshow-gallery__item">
	    <img class="slideshow-gallery__item__image" src="http://vignette3.wikia.nocookie.net/onepiece/images/1/10/Hand_Island_Infobox.png/revision/latest?cb=20140916180507" alt="" />
	    <p class="slideshow-gallery__item__title">#{ slideshow.title}</p>
    </a> -->
</ui:repeat>  
</div>
</body>
</html>

javaee7wildfly/src/main/webapp/slideshow-jsf/slideshow.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <f:metadata>
        <f:viewParam name="id" value="#{ slideshowBean.id}" /> <!--  slideshow id -->
        <f:viewParam name="index" value="#{ slideshowBean.index}" /> <!--  slide index -->
        <f:viewAction action="#{ slideshowBean.load }" /> <!-- load the slideshow and the slide -->
    </f:metadata>
    
<h:head>
    <title>Slideshow</title>
    <h:outputStylesheet name="css/reset.css" />
    <h:outputStylesheet name="css/slideshow.css" />
</h:head>
<body>
    <div class="container">
        <div class="slideshow">
            <h1 class="slideshow__title">#{ slideshowBean.slideshow.title }</h1>
            
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1"
                class="slideshow__slide"
                viewport="0 0 #{ slideshowBean.slideshow.width } #{ slideshowBean.slideshow.height }"
                xmlns:xlink="http://www.w3.org/1999/xlink">
                
                <ui:repeat value="#{ slideshowBean.slide.slideElements}" var="e">
                    <h:outputText value="#{slideshowBean.generateHTMLMarkupForSlideElement(e)}" escape="false"/>
                </ui:repeat>
            </svg>

            </div>
        </div>
        
            <div class="slideshow__hud">
                <h:link class="slideshow__hud__link slideshow__hud__link--hidden"
                        outcome="/slideshow-jsf/slideshow"
                        value="previous"
                        rendered="#{ slideshowBean.index le 0}">
                       <f:param name="id" value="#{ slideshowBean.slideshow.id }"/>
                       <f:param name="index" value="#{ slideshowBean.index - 1 }"/>
                </h:link>
                
                <h:link class="slideshow__hud__link"
                        outcome="/slideshow-jsf/slideshow"
                        value="previous"
                        rendered="#{ slideshowBean.index gt 0}">
                       <f:param name="id" value="#{ slideshowBean.slideshow.id }"/>
                       <f:param name="index" value="#{ slideshowBean.index - 1 }"/>
                </h:link>
                
                <h:link class="slideshow__hud__link slideshow__hud__link--hidden"
                        outcome="/slideshow-jsf/slideshow"
                        value="next"
                        rendered="#{ slideshowBean.index ge (slideshowBean.slideshow.size() - 1) }">
                       <f:param name="id" value="#{ slideshowBean.slideshow.id }"/>
                       <f:param name="index" value="#{ slideshowBean.index - 1 }"/>
                </h:link>
                
                <h:link class="slideshow__hud__link"
                        outcome="/slideshow-jsf/slideshow"
                        value="next"
                        rendered="#{ slideshowBean.index lt slideshowBean.slideshow.size() - 1 }">
                       <f:param name="id" value="#{ slideshowBean.slideshow.id }"/>
                       <f:param name="index" value="#{ slideshowBean.index + 1 }"/>
                </h:link>

                <p class="slideshow__hud__index">#{ slideshowBean.index + 1 }/ #{ slideshowBean.slideshow.size() }</p>
                                
            </div>

</body>
</html>